[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#00CC96"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false
